### ISSUE TITLE
Integrate Travis CI to run the RML Test Suite after each release

### ISSUE THREAD

**Issue by collarad** [SDM-TIB/SDM-RDFizer#10]
It would be great to integrate Travis CI to automatically run the RML Test Suit after each release of commit.

**Comment by WolfgangFahl** [comment]
Please contact me - I'll gladly help with this issue.

**Comment by dachafra** [comment]
I have created a resource to automatically run and generate the report: https://github.com/dachafra/rml-test-cases-support

**Comment by dachafra** [comment]
@eiglesias34 I think we can close this issue
