### ISSUE TITLE
Can we count the number of triples generated during semantication?

### ISSUE THREAD

**Issue by Gautamshahi** [SDM-TIB/SDM-RDFizer#105]
I am using Rdfizer to get the number of stratifications; once I load the TTL output file to RDFLib, the number of triples is less.

To verify the issue, can I coun the number of triples during semantication?

**Comment by dachafra** [comment]
Hi @Gautamshahi, could you maybe run these bash commands and give us the results?

- `wc -l your_rdfizer_output_file.ttl`: will give us the total number of triples from the rdfizer
- `sort your_rdfizer_output_file.ttl | uniq > output_without_duplicates.ttl` and then again  `wc -l output_without_duplicates.ttl` to know if rdfizer is generating duplicate values
