### ISSUE TITLE
For XML parsing, is there still a problem with xmlns ?

### ISSUE THREAD

**Issue by FabianCretton** [SDM-TIB/SDM-RDFizer#117]
**Describe the bug**
Same problem as described by #81
If xmlns is present in the <students> tag, then nothing is generated and the output .ttl file is empty

I tried to adapt the xPath with:
` rml:iterator "/*[local-name()='students']/*[local-name()='student']"`
But the output ttl file was still empty.

**To Reproduce**
Run the example provided in the .zip file

By removing the xmlns element, than everything works fine

**Desktop (please complete the following information):**
- Ubuntu 22.04
- Python 3.10.12
- rdfizer: 4.7.4.11

Thank you for your help

[xmlnsIssue.zip](https://github.com/user-attachments/files/17075135/xmlnsIssue.zip)

**Comment by eiglesias34** [comment]
Dear @FabianCretton,

First of all, thank you for using the SDM-RDFizer. I apologize for the delay in getting back to you regarding this issue. I have found the problem and fixed it. Please test it out so we can close this issue. Please note that I am currently adding the function to print the output in turtle format for XML data sources. For the time being, please use the n-triples output format.

Sincelery,
Enrique

**Comment by FabianCretton** [comment]
Thank you very much @eiglesias34, it works fine!
Best regards
Fabian
