### ISSUE TITLE
module rdfizer.triples_map.TriplesMap cannot be loaded

### ISSUE THREAD

**Issue by VladimirAlexiev** [SDM-TIB/SDM-RDFizer#15]
When I download the most recent master and start the tool as described, I get this error:

```
Traceback (most recent call last):
  File "../SDM-RDFizer/rdfizer/rdfizer/semantify.py", line 11, in <module>
    from rdfizer.triples_map import TriplesMap as tm
ModuleNotFoundError: No module named 'rdfizer'
```

I think it's not enough to have a file `rdfizer/triples_map/TriplesMap.py` but you must also somehow add it to the module load path (I'm no python expert).

Later on the file goes:
```
from .functions import *
```
I tried adding such leading dot `rdfizer.triples_map` but got error `No module named '__main__.rdfizer'; '__main__' is not a package`

**Comment by VladimirAlexiev** [comment]
I overcame this by adding the respective folder to PYTHONPATH:
```
PYTHONPATH=../SDM-RDFizer/rdfizer/ python ../SDM-RDFizer/rdfizer/rdfizer/semantify.py -c config.ini
```

But then I got this error:
```
Traceback (most recent call last):
  File "../SDM-RDFizer/rdfizer/rdfizer/semantify.py", line 20, in <module>
    from .functions import *
ModuleNotFoundError: No module named '__main__.functions'; '__main__' is not a package
```

**Comment by dachafra** [comment]
Hi @VladimirAlexiev, thanks for the feedback?
Could you send us the mapping you are using and the config details (or file)?

**Comment by eiglesias34** [comment]
Hello @VladimirAlexiev, can you show me how you were running the RDFizer when you got the error?

**Comment by VladimirAlexiev** [comment]
Sorry, can't share the mapping (not just yet anyway).

I'm running from a sibling directory: see `../SDM-RDFizer/rdfizer/rdfizer/semantify.py`. I'm not running from the tools home directory.

After the imports block, there is something more that doesn't make sense to me
```
try:
	from triples_map import TriplesMap as tm
except:
	from .triples_map import TriplesMap as tm	
```

**Comment by eiglesias34** [comment]
Please run the RDFizer like this:
`python3 run_rdfizer.py configfile`

From the directory where run_rdfizer.py file is located.

**Comment by VladimirAlexiev** [comment]
I don't think it's ok for a tool to be able to run only from its home directory.
You don't have to change to python's home dir before you can run it, right?

**Comment by dachafra** [comment]
the way to run the tool is: python3 (or path to the python3) [..]/SDM-RDFizer/rdfizer/run_rdfizer.py /path-to-config-file. 
You can call the tool from any dir and it's also not needed to change the python dir

**Comment by VladimirAlexiev** [comment]
I confirm this works:
```
python ../SDM-RDFizer/rdfizer/run_rdfizer.py config.ini
```

# Please fix the instructions at https://github.com/SDM-TIB/SDM-RDFizer/tree/master/rdfizer. That README is 15m old, and suggests to invoke semantify.py directly.
# I run with `python` (which is Python 3.7.0). If I try with `python3` I get this error: `ModuleNotFoundError: No module named 'rdflib'` although pip said `Requirement already satisfied: rdflib==4.2.2 in ...python\python37\lib\site-packages`. So please require python 3 but change the instructions to run `python`

**Comment by dachafra** [comment]
Thanks for your valuable issue @VladimirAlexiev.
README and requirements.txt inside folder rdfizer are removed to avoid confusions. 
The correct ones are in the root folder
