### ISSUE TITLE
Document all config options

### ISSUE THREAD

**Issue by VladimirAlexiev** [SDM-TIB/SDM-RDFizer#16]
Document all options that can be in config.ini (the provided example is not complete).

In particular, from https://github.com/SDM-TIB/SDM-RDFizer/blob/master/rdfizer/rdfizer/semantify.py#L3273 and around I learned there are options `dbType`, `user`, `password`, `db`, and what `all_in_one_file` means.

Now digging to understand what `enrichment` means.

**Comment by VladimirAlexiev** [comment]
Ok, I found https://github.com/SDM-TIB/SDM-RDFizer/wiki/Install&Run#parameters-to-run-the-sdm-rdfizer. Please
- point to these pages from the README
- use bullets for the params, not long code lines that one needs to scroll to read

**Comment by dachafra** [comment]
Done. Links are now in the main README and explanation for the parameters are included

**Comment by VladimirAlexiev** [comment]
@dachafra 
- `*enrichment` doesn't show as a bullet
- Remove https://github.com/SDM-TIB/SDM-RDFizer/wiki/FAQ `Q: How is the SDM-RDFizer configured?` and replace it with a link to the other section
