### ISSUE TITLE
hardcoded databases at localhost

### ISSUE THREAD

**Issue by VladimirAlexiev** [SDM-TIB/SDM-RDFizer#19]
You got some spots that open databases at localhost (`connector` is mysql and `psycopg2` is postgres):
```
   2478: db = connector.connect(host="localhost", port=3306, user="root", password="06012009mj")
   2496: db = connector.connect(host = "localhost", port = 3306, user = "root", password = "06012009mj")
   2946: db = psycopg2.connect( host="localhost", user="postgres", password="postgres", dbname="" )
   2960: db = psycopg2.connect( host="localhost", user="postgres", password="postgres", dbname="" )
```
- what is this for?
- how can you be sure that localhost has such databases running?
- is it a good idea to use hardcoded passwords? In particular the `06012009mj` password looks like some secret?

**Comment by eiglesias34** [comment]
I removed the hardcoded lines.
