### ISSUE TITLE
check for existence of config file

### ISSUE THREAD

**Issue by VladimirAlexiev** [SDM-TIB/SDM-RDFizer#22]
I have a file `run.sh` that looks like this:
```
python ../SDM-RDFizer/rdfizer/run_rdfizer.py config.ini
```

However it was saved with DOS line endings. When I run it, I get this error
```
$ ./run.sh 
Traceback (most recent call last):
  File "../SDM-RDFizer/rdfizer/run_rdfizer.py", line 3, in <module>
    semantify(str(sys.argv[1]))
  File "...\SDM-RDFizer\rdfizer\rdfizer\semantify.py", line 3217, in semantify
    duplicate = config["datasets"]["remove_duplicate"]
  File "...\Programs\Python\Python37\lib\configparser.py", line 958, in __getitem__
    raise KeyError(key)
KeyError: 'datasets'
```
The reason is that it can't find `config.ini\r` but the error doesn't say that so it's confusing. (Converting to Unix line endings with `d2u config.ini` fixes this problem)

Please check for existence of the config file and print its name and the error code if it can't be opened.

**Comment by eiglesias34** [comment]
I have added the verification of the existence of the configuration to the SDM-RDFizer.
