### ISSUE TITLE
Wiki - install and run instructions not quite correct

### ISSUE THREAD

**Issue by markwilkinson** [SDM-TIB/SDM-RDFizer#26]
The instructions in the Wiki seem to be incorrect.  The instruction below (copied from your wiki) will not result in a POST, but rather a GET... I have tried a few different POST curls of the config.ini file, and so far none of them have resulted in success.  Any suggestions?

----------------
Send a POST request with the configuration file to RDFizer the file

curl localhost:4000/graph_creation/data/your-config-file.ini

----------------

**Comment by eiglesias34** [comment]
The API for the docker image accepts both POST and GET requests. 

When executing the curl command the path that is given must be the location of the data within the docker image. For example, curl localhost:4000/graph_creation/data/cikm_example/configfile.ini. Also, the configuration and mapping file must reflex this as well. If curl was executed and output was generated this could mean that path towards the configuration file wasn't given correctly, the mapping doesn't have the correct path or files weren't uploaded correctly. 

Here's a video example of how to run the RDFizer. https://www.youtube.com/watch?v=DpH_57M1uOE

Also, if you keep having trouble with the RDFizer, please send me the log of the docker image so I can give you a better solution if necessary.

**Comment by eiglesias34** [comment]
Of course, I wish to solve this problem. But, if you need to convert data urgently you could execute the RDFizer locally with python.

`python3 run_rdfizer.py configfile.ini`

**Comment by markwilkinson** [comment]
it's all good!  i got it working by GET - my error was not understanding that /graph_creation/ was a required part of the URL - I was trying to point directly at the path of the config file.
Sorry!

**Comment by eiglesias34** [comment]
Very good. I will update the wiki so that it says GET not POST. Thank you for your interest in the RDFizer.

**Comment by markwilkinson** [comment]
can you tell me where the log is so that I can troubleshoot?

**Comment by eiglesias34** [comment]
When I mean the log I mean the docker log.

`docker logs container_id`
