### ISSUE TITLE
Error  with Json Source files

### ISSUE THREAD

**Issue by FrankBorrero** [SDM-TIB/SDM-RDFizer#33]
[Json.zip](https://github.com/SDM-TIB/SDM-RDFizer/files/5261124/Json.zip)
Hi, Using SDM-RDFIzer  with json files im geting error:

Semantifying KGCase2david.nt...
Traceback (most recent call last):
  File "/home/fborrero/SDM-RDFizer/SDM-RDFizer/rdfizer/run_rdfizer.py", line 3, in <module>
    semantify(str(sys.argv[1]))
  File "/home/fborrero/SDM-RDFizer/SDM-RDFizer/rdfizer/rdfizer/semantify.py", line 3646, in semantify
    number_triple += executor.submit(semantify_file, triples_map, triples_map_list, output_file_descriptor, wr, config[dataset_i]["name"], data[0]).results()
AttributeError: 'Future' object has no attribute 'results'.

The data sourcefiles, and the mapping files were use  with  RMLmapper, and RockterRML and no problems were presented at the moment of generating the graph. 

This let me assume that there is not any problem with source files or the mapping files as it worked with the other RDFizers.

Im attaching the source files used, also the mapping files and the configfile.ini for reproducibility.

**Comment by eiglesias34** [comment]
I fixed the problem. I also ran the data that was given and was processed with no problem. Please confirm, so that we can close this issue.

**Comment by FrankBorrero** [comment]
It was executed again and it was successful.
Thanks.
