### ISSUE TITLE
mysql-connector-python outdated version

### ISSUE THREAD

**Issue by ArenasGuerreroJulian** [SDM-TIB/SDM-RDFizer#37]
Hi!!

**Describe the bug**
Using MySQL DB I was getting error:

```mysql.connector.errors.InterfaceError: 2055: Lost connection to MySQL server at 'localhost:3306', system error: 1 [SSL] internal error (_ssl.c:1123)```

**Environment**
I am using mysql:5.7 docker image, and running RDFizer in Ubuntu 20.04

**Possible solution**
I solved this my upgrading mysql-connector-python to latest version (8.0.22), maybe you can consider using this version in requirements.txt (currently 8.0.11)

:)

**Comment by eiglesias34** [comment]
The requirements have been updated. Thank you for the suggestion.
