### ISSUE TITLE
More triples generated than expected

### ISSUE THREAD

**Issue by ArenasGuerreroJulian** [SDM-TIB/SDM-RDFizer#42]
Hi!!!

When I instantiate the KG for GTFS-Madrid-benchmark (size 1) I get 570354 triples. If I duplicate the same source in the config I get 571616 triples. IMO this is wrong since instantiating the same KG twice should generate the same triples and the number of triples obtained should be the same. I put the example config files:

This config generates 570354 triples:
```
[default]
main_directory: .

[datasets]
number_of_datasets: 1
output_folder: ${default:main_directory}/output
remove_duplicate: yes
all_in_one_file: yes
name: demo_stats
enrichment: yes
dbtype: mysql

[dataset1]
name: demo
mapping: ../../testing/gtfs-rdb.rml.ttl
user: root
password: dba
host: localhost
port: 3306
db: gtfs
```

This config generates 571616 triples:
```
[default]
main_directory: .

[datasets]
number_of_datasets: 2
output_folder: ${default:main_directory}/output
remove_duplicate: yes
all_in_one_file: yes
name: demo_stats
enrichment: yes
dbtype: mysql

[dataset1]
name: demo
mapping: ../../testing/gtfs-rdb.rml.ttl
user: root
password: dba
host: localhost
port: 3306
db: gtfs

[dataset2]
name: demrep
mapping: ../../testing/gtfs-rdb.rml.ttl
user: root
password: dba
host: localhost
port: 3306
db: gtfs
```

NOTE THAT the source is the same and the mapping are also similar (same mapping file).

**Comment by dachafra** [comment]
why do you want to describe in the config file two sources that are exactly the same? It doesn't make sense

**Comment by eiglesias34** [comment]
Hello @ArenasGuerreroJulian. Could you run the experiment again but this time run it with the option all_in_one_file as no. This will cause the extra triples will end up in the second file. Please tell me the result, this will tell me where the problem is.

**Comment by ArenasGuerreroJulian** [comment]
I have tested again, and seems to be working right, it is always generating 570354 triples. Probably I was doing something wrong :'(

**Comment by ArenasGuerreroJulian** [comment]
1.
