### ISSUE TITLE
Json source attribute missing

### ISSUE THREAD

**Issue by jayansene** [SDM-TIB/SDM-RDFizer#44]
if some object in json missed  a attribute which is refered in template it throws error.
Shouldn't it suppose just pass that value?

**Comment by eiglesias34** [comment]
Hello,

We use SDM-RDFizer for our projects. To us, it's convenient that the SDM-RDFizer would stop when an attribute is missing. I changed the SDM-RDFizer so it won't stop when an attribute is missing. But, it will still give a message when an attribute is missing. Please confirm if the SDM-RDFizer performed as desired, so we can close the issue.

Thank you for using the SDM-RDFizer.

**Comment by jayansene** [comment]
Hi..thanks.. its working..I found another YARRRML converted mapping throws error..I will post it...
