### ISSUE TITLE
SDM RDFizer Installation

### ISSUE THREAD

**Issue by jameel89** [SDM-TIB/SDM-RDFizer#47]
How to Install SDM FIZER and generate RDF files from datasets.

**Comment by dachafra** [comment]
Hi, 
There is complete information about how to install and use the SDM-RDFizer in our wiki: https://github.com/SDM-TIB/SDM-RDFizer/wiki/Install&Run

The basic requirements are:
- Mappings following RML
- Configuration file: https://github.com/SDM-TIB/SDM-RDFizer/wiki/The-Parameters-of-the-Configuration-file
- Python 3 or docker, depending on your own requirements.
