### ISSUE TITLE
Fail gracefully when JSONPath (or XPath) does not resolve to a string

### ISSUE THREAD

**Issue by mielvds** [SDM-TIB/SDM-RDFizer#49]
**Describe the bug**
RDFizer crashes when a JSONPath in `rml:reference` resolves to a JSON object. 

**Expected behavior**
A JSON serialisation of the object (agreed, wouldn't make sense, but it's what the user asked) or a nice error message would be better.

**Comment by eiglesias34** [comment]
Could you give me an example? So I can have a better grasp of what you are saying.

**Comment by mielvds** [comment]
Given the example from https://github.com/SDM-TIB/SDM-RDFizer/issues/48 but with

```
rr:subjectMap [
    rr:template "http://example.org/{city}";
    rr:class ex:City
  ];
```

**Comment by eiglesias34** [comment]
I understand now. I going to add an error message. I feel that the user needs to be more specific in this case.

**Comment by eiglesias34** [comment]
I updated the SDM-RDFizer so that it will return an error message. The SDM-RDFizer itself won't stop running but it will not generate the triples related to this triples map.
