### ISSUE TITLE
Generation of term maps using rml:reference

### ISSUE THREAD

**Issue by ArenasGuerreroJulian** [SDM-TIB/SDM-RDFizer#50]
Hi there!

From R2RML spec (it applies since RML extends R2RML):

```
Graph maps are themselves term maps
```

and

```
A term map MUST be exactly one of the following:

    a constant-valued term map,
    a column-valued term map,
    a template-valued term map.
```

Taking a look to the mapping parsing query used in SDM-rdfizer:

```
	# Predicate -----------------------------------------------------------------------
		OPTIONAL {
			?triples_map_id rr:predicateObjectMap ?_predicate_object_map .
			
			OPTIONAL {
				?triples_map_id rr:predicateObjectMap ?_predicate_object_map .
				?_predicate_object_map rr:predicateMap ?_predicate_map .
				?_predicate_map rr:constant ?predicate_constant .
			}
			OPTIONAL {
				?_predicate_object_map rr:predicateMap ?_predicate_map .
				?_predicate_map rr:template ?predicate_template .
			}
			OPTIONAL {
				?_predicate_object_map rr:predicateMap ?_predicate_map .
				?_predicate_map rml:reference ?predicate_reference .
			}
			OPTIONAL {
				?_predicate_object_map rr:predicate ?predicate_constant_shortcut .
			 }
```

I think it is not possible to generate graph terms with rml:reference at this moment. It think it is something that will not be used, but I assume it is needed to fully comply with RML spec.

Best,
Julián

**Comment by eiglesias34** [comment]
Hello

I added the necessary parts to the parser.

`OPTIONAL {?_predicate_object_map rr:graph ?predicate_object_graph .}
  OPTIONAL { ?_predicate_object_map  rr:graphMap ?_graph_structure .
				  ?_graph_structure rr:constant ?predicate_object_graph  . }
  OPTIONAL { ?_predicate_object_map  rr:graphMap ?_graph_structure .
				  ?_graph_structure rr:template ?predicate_object_graph  . }	
  }`
