### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'keys'

### ISSUE THREAD

**Issue by mielvds** [SDM-TIB/SDM-RDFizer#57]
**Describe the bug**
The statement [`row = row[tp]`](https://github.com/SDM-TIB/SDM-RDFizer/blob/master/rdfizer/rdfizer/functions.py#L254) sets `row` to `None` which makes https://github.com/SDM-TIB/SDM-RDFizer/blob/master/rdfizer/rdfizer/functions.py#L318 error. Probably this is again because a key is missing in json, which is quite common.

I noticed you're not using a JSONPath library, could that be? Without unittests (the RML test cases won't protect you from JSONPath implementation bugs), this is really shooting in the dark. I will stop opening issues for now, because this way of working is just too time consuming I'm afraid.

**Comment by eiglesias34** [comment]
Hi,

I made sure that before executing `row = row[tp]` that tp (which is the key) is within the current dictionary. Meaning if `row` was set to `None`, at that level of the dictionary the value is `None`. I added the verification if `row` is `None` the triple is not generated. About using the JSONPath library I might add it in a future version of the SDM-RDFizer. Please tell me if the change I made fixes the issue.

**Comment by mielvds** [comment]
That fixes it! thx
