### ISSUE TITLE
rr:template is URL encoded when rr:termType is rr:Literal

### ISSUE THREAD

**Issue by mielvds** [SDM-TIB/SDM-RDFizer#58]
**Describe the bug**
When writing

```
rr:predicateObjectMap [ 
    rr:predicate foaf:mbox; 
    rr:objectMap [ rr:template "mailto:{email}"; rr:termType rr:Literal ]
  ].
```
the output is `<http://data.meemoo.be/people/0c23fa9b-1363-0ae6-a449-029a7d29507f> <http://xmlns.com/foaf/0.1/mbox> "mailto:x%40y.com".` This should only happen when `rr:termType rr:IRI`.

**Comment by eiglesias34** [comment]
Just to be clear, I should not apply the transformation. It should stay has <mailto:x%40y.com>.

**Comment by mielvds** [comment]
I think the output should be `<http://data.meemoo.be/people/0c23fa9b-1363-0ae6-a449-029a7d29507f> <http://xmlns.com/foaf/0.1/mbox> "mailto:x@y.com"`

The [R2RML](https://www.w3.org/TR/r2rml/#from-template) spec states:

```
4. If the term type is rr:IRI, then replace the pair of curly braces with an IRI-safe version of value; otherwise, replace the pair of curly braces with value
```

**Comment by eiglesias34** [comment]
I'm sorry, I misunderstood the issue. I thought you were talking about the quotes, not that @ was encoded. Anyways, I just fixed it.
