### ISSUE TITLE
Base URI in Subject of N-Triples RDF File

### ISSUE THREAD

**Issue by juanbm99** [SDM-TIB/SDM-RDFizer#61]
**Describe the bug**
When generating data from a CSV throught an RML mapping, the subject of the N-Triples contains the base URI

**To Reproduce**
Steps to reproduce the behavior (and resources):
1. Get CSV File
2. Get an RML mapping file without self-join and child/parent relations
3. Use RDFizer to generate the data

**Expected behavior**
N-Triples should only contain the URI specified for the subject

**Screenshots**
![image](https://user-images.githubusercontent.com/43373725/111068724-415ff500-84ca-11eb-83e3-f3064538cff2.png)
![image](https://user-images.githubusercontent.com/43373725/111068747-58064c00-84ca-11eb-8164-17a0672cadfa.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Comment by dachafra** [comment]
@juanbm99 could you send us the link to the mapping and csv data?

**Comment by juanbm99** [comment]
Mapping: https://github.com/juanbm99/TFG-OpenCityData-JuanBernal/blob/main/data/mappings/ruido2021-RML.rml
CSV: https://github.com/juanbm99/TFG-OpenCityData-JuanBernal/blob/main/data/preprocessed/RuidoDiario2021/RuidoDiario2021_v2.csv

**Comment by eiglesias34** [comment]
Dear @juanbm99,

Thank you for using the SDM-RDFizer.

I fixed the issue. I ran it with the data and mapping provided and didn't get the error anymore. Please test it out, so we can close this issue. Please note that the changes I made are not in the library yet.

Thank you again.
Enrique

**Comment by juanbm99** [comment]
Perfect, that work!
Thank you
