### ISSUE TITLE
Language tags missing

### ISSUE THREAD

**Issue by fyedro** [SDM-TIB/SDM-RDFizer#63]
Trying to include language tags in strings, but only the @en and @es tags are included, the Italian and French tags are ignored. This is a snippet of the code:

:pom_2 a rr:PredicateObjectMap.
:map_idConcepto_0 rr:predicateObjectMap :pom_2.
:pm_2 a rr:PredicateMap.
:pom_2 rr:predicateMap :pm_2.
:pm_2 rr:constant skos:prefLabel.
:pom_2 rr:objectMap :om_2.
:om_2 a rr:ObjectMap;
    rml:reference "termEN";
    rr:termType rr:Literal;
    rr:language "en".
:pom_3 a rr:PredicateObjectMap.
:map_idConcepto_0 rr:predicateObjectMap :pom_3.
:pm_3 a rr:PredicateMap.
:pom_3 rr:predicateMap :pm_3.
:pm_3 rr:constant skos:prefLabel.
:pom_3 rr:objectMap :om_3.
:om_3 a rr:ObjectMap;
    rml:reference "termES";
    rr:termType rr:Literal;
    rr:language "es".
:pom_4 a rr:PredicateObjectMap.
:map_idConcepto_0 rr:predicateObjectMap :pom_4.
:pm_4 a rr:PredicateMap.
:pom_4 rr:predicateMap :pm_4.
:pm_4 rr:constant skos:prefLabel.
:pom_4 rr:objectMap :om_4.
:om_4 a rr:ObjectMap;
    rml:reference "termIT";
    rr:termType rr:Literal;
    rr:language "it".
:pom_5 a rr:PredicateObjectMap.
:map_idConcepto_0 rr:predicateObjectMap :pom_5.
:pm_5 a rr:PredicateMap.
:pom_5 rr:predicateMap :pm_5.
:pm_5 rr:constant skos:prefLabel.
:pom_5 rr:objectMap :om_5.
:om_5 a rr:ObjectMap;
    rml:reference "termFR";
    rr:termType rr:Literal;
    rr:language "fr".

**Comment by dachafra** [comment]
@fyedro could you send us (by link or uploading them) the csv file and the mapping rules?

**Comment by fyedro** [comment]
Here you have a small csv and the ttl file:
TTL:
[OutputSmarterp-rml.ttl.zip](https://github.com/SDM-TIB/SDM-RDFizer/files/6195387/OutputSmarterp-rml.ttl.zip)
CSV:
[smarterp.zip](https://github.com/SDM-TIB/SDM-RDFizer/files/6195389/smarterp.zip)

**Comment by dachafra** [comment]
The issue has been solved, thanks @eiglesias34 and @fyedro
