### ISSUE TITLE
'TypeError: element indices must be integers' when using XML

### ISSUE THREAD

**Issue by amirwesthoff** [SDM-TIB/SDM-RDFizer#65]
Hi - I want to use rdfizer as a command line tool with a configuration file, but I run into an error when doing it for an XML file:

![image](https://user-images.githubusercontent.com/41545158/119812529-864fd100-bee8-11eb-9263-502e28109c6e.png)

I've been able to successfully run the example with the CSV file, and, after the required changes to the mapping and configuration files, for a JSON file. For the JSON and XML mapping, I simply reused the examples from https://rml.io/specs/rml/#overview, section 3.2 and section 3.3. Having changed the file locations, it looks like the program is able to locate the necessary files.

**To Reproduce**
Steps to reproduce the behavior (and resources):

1. Create/put the source file:
![image](https://user-images.githubusercontent.com/41545158/119813268-59e88480-bee9-11eb-98a8-ee14dcf90030.png)
(Copied from rml.io into a file called Transport.xml)

2. Modify/create config_xml.ini:
![image](https://user-images.githubusercontent.com/41545158/119813592-c794b080-bee9-11eb-9d19-7d6b394baeb1.png)

3. Modify/create mapping_xml.ttl:
![image](https://user-images.githubusercontent.com/41545158/119813669-d8ddbd00-bee9-11eb-8878-cf80e36f06b0.png)

4. Run
Run command: 'python rdfizer/run_rdfizer.py example/config_xml.ini'

**Expected behavior**
I would have expected this to successfully complete, just like it did for the CSV and JSON files.

**Screenshots**
See above for screenshots.

**Additional comments**
I am on Windows 10 using Python 3.9.1.

Hopefully this will serve to spot whether the error is on my side or not?

**Comment by dachafra** [comment]
thanks for reporting the bug @amirwesthoff, we will try to solve it asap

**Comment by eiglesias34** [comment]
Hello,

I fixed the problem. The example in question has been processed without issue. Please test it out and confirm that the problem has been solved. Please note that the changes made were to source files. The library will be updated after we close this issue.

Thank you again for your interest in the SDM-RDFizer.

Sincerely,
Enrique Iglesias/

**Comment by amirwesthoff** [comment]
Hi Enrique,

I have just tested it, my problem is solved. Many thanks for the quick follow-up!
