### ISSUE TITLE
[Question] Support for custom functions?

### ISSUE THREAD

**Issue by amirwesthoff** [SDM-TIB/SDM-RDFizer#66]
Hi,

Does/will SDM-RDFizer support custom functions in mappings, based on the [Function Ontology](https://fno.io/rml/) (fno) or otherwise? Would be great if this is possible, perhaps there is a way that I haven't discovered yet?

Thanks,
Amir

**Comment by samiscoding** [comment]
Hi, 

Interesting question! In fact, for interpreting functions we have a specific engine called [FunMap](https://github.com/SDM-TIB/FunMap) able to process functions based on FnO into equivalent RML mappings without functions. Currently, we're working on extending FunMap as well as having a customizable version very soon! Happy to receive your feedback on using it :)

**Comment by eiglesias34** [comment]
Hello,

Currently, there is no plan to add custom mappings to the SDM-RDFizer. As mentioned by my colleague, we do have RML engine (FunMap) that is capable of processing custom functions based on FnO into equivalent RML mappings without functions. This processing includes the execution of the functions and the projection of the data sources. The engine replaces the call to functions from the mapping into joins between triples maps.

Thank you for your interest in the SDM-RDFizer

**Comment by amirwesthoff** [comment]
Hi @samiscoding aand @eiglesias34, thank you for your quick reply and will definitely have a look :)
