### ISSUE TITLE
Proposition to improve the RDFizer packaging

### ISSUE THREAD

**Issue by vemonet** [SDM-TIB/SDM-RDFizer#70]
Hi, I noticed the implementation of the RDFizer is taking a lot of weird roads to finally get to the actual RDF conversion

For example a typical deployment is:
* Deployed using Docker
* Inside the Docker container there is a script `app.py` that starts an API (without proper OpenAPI documentation!)
* This API is then called by passing the path of the `config.ini` file to the URL (which is not user friendly because it requires the user to write down the exact relative path the undocumented API is expecting)
* When the API is called the `rdfize` package is called used `os.system` 
* The rdfizer package actually only calls the `Semantify(config_file)` function

It is a lot of complex steps for doing something that could be done much more easily with less breaking points 

Normally you should be able to do it directly via the command line without the need for starting an endpoint. Here are a few examples of what the different command to run the rdfizer could look like:

```bash
# Without config file: 
rdfizer -m mapping.ttl -o output
# With config file
rdfizer -c config.ini
# With Docker
docker run -it -v $(pwd):/data rdfizer -c config.ini
```

And next to this you could easily still have an API using OpenAPI standards that allow the user to run it the way it is currently run 

I am planning to take a look into it and make the packaging a bit more tight and intuitive for the users (adding direct CLI option, adding OpenAPI/swagger docs to the API

Is that something that could be interesting to you, or is the process set in stone? @eiglesias34 @samiscoding @dachafra 

If you are interested in contributions, is there anything I need to know to make the change in a way that work for you?

**Comment by dachafra** [comment]
@vemonet the engine is already available in PyPi (https://pypi.org/project/rdfizer/) so you can easily run it as you are mentioned:
```
python3 -m pip install rdfizer
python3 -m rdfizer -c config.ini
```
The docker API was included in the very first versions of the engine for ensuring the reproducibility of our research experiments

**Comment by eiglesias34** [comment]
Hello @vemonet,

First of all, thank you for your interest in the SDM-RDFizer. The execution of the SDM-RDFizer is not set in stone for the time being. Currently, we do have some improvements planned for the SDM-RDFizer. We can consider the simplification of the execution of an improvement.

Sincerely,
Enrique
