### ISSUE TITLE
Support for XPATH expressions

### ISSUE THREAD

**Issue by jo-fra** [SDM-TIB/SDM-RDFizer#75]
**Describe the bug**
In my RML mapping I am using XPATH expressions in the iterator for the source like e.g. 

```
  ...
  rml:logicalSource [
      rml:source "source.xml";
      rml:referenceFormulation ql:XPath;
      rml:iterator "//SupportedRoleClass[@RefRoleClassPath='AutomationProjectConfigurationRoleClassLib/AutomationProject']"
  ];
  ...
```
However, with this mapping RDFizer generates no triples at all. 
With RMLMapper the triples are generated as expected.

**Expected behavior**
Should handle XPATH expressions in rml:iterator definition

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Version [4.0.1.3]

**Comment by dachafra** [comment]
@jo-fra would be possible to share a piece of the data for doing the proper testing after fixing the bug?

**Comment by jo-fra** [comment]
@dachafra an example piece of data would be:
**`source.xml`**
```XML
<?xml version="1.0" encoding="utf-8"?>
<InstanceHierarchy Name="APC Sample Instance Hierarchy">
  <InternalElement ID="9088524c-0041-47bd-af69-93d3e745f364" Name="Demo">
    <SupportedRoleClass RefRoleClassPath="AutomationProjectConfigurationRoleClassLib/AutomationProject" />
  </InternalElement>
</InstanceHierarchy>
```

The mapping file:
**`mapping.ttl`**
```Turtle
@prefix rr: <http://www.w3.org/ns/r2rml#> .
@prefix rml: <http://semweb.mmlab.be/ns/rml#> .
@prefix ql: <http://semweb.mmlab.be/ns/ql#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

@prefix exont: <http://example.com/ontology#> .
@base <http://example.com/instance/> .

<AutomationProjectMapping> a rr:TriplesMap;
  rml:logicalSource [
    rml:source "source.xml";
    rml:referenceFormulation ql:XPath;
    rml:iterator "//SupportedRoleClass[@RefRoleClassPath='AutomationProjectConfigurationRoleClassLib/AutomationProject']"
  ];
  rr:subjectMap [
    rr:template "http://example.com/instance/{../@ID}";
    rr:class exont:AutomationProject;
  ];
  rr:predicateObjectMap [
    rr:predicate rdfs:label;
    rr:objectMap [ 
      rml:reference "../@Name" 
    ]
  ].
```

The expected output generated by RML mapper:
**`output.ttl`**
```Turtle
@prefix exont: <http://example.com/ontology#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

<http://example.com/instance/9088524c-0041-47bd-af69-93d3e745f364> a exont:AutomationProject;
  rdfs:label "Demo" .

```

**Comment by eiglesias34** [comment]
Hello @jo-fra,

First of all, thank you for your interest in the SDM-RDFizer. I was able to find the problem and fix it. Please test it out. Please note that I updated the code, not the library. After receiving the confirmation that the problem has been solved I will update the library and close the issue.

Thank you again,
Enrique Iglesias

**Comment by eiglesias34** [comment]
Thank you again for your interest in the SDM-RDFizer. I going to close this issue now. All the changes have been updated in the library.
