### ISSUE TITLE
Wrong number of triples obtained with large_file in yes

### ISSUE THREAD

**Issue by jatoledo** [SDM-TIB/SDM-RDFizer#77]
Hi!

We are running SDM-RDFizer v4.0.5 with GTFS-Madrid-Bench. For the case of CSV with scaling factor 1 we obtained a different number of triples than with rmlmapper and Morph-KGC (that we have verified that obtain the same number of triples). Also for SDM-RDFizer, depending on the execution, a different number of triples are obtained (e.g. for some runs it obtains 103038 triples and for others it obtains 337121 number of triples). The config file that we are using is:

```
[default]
main_directory: .

[datasets]
number_of_datasets: 1
output_folder: ${default:main_directory}/output_rdfizer
remove_duplicate: yes
all_in_one_file: yes
name: gtfs
enrichment: yes
large_file: yes
ordered: yes

[dataset1]
name: gtfs
mapping: ${default:main_directory}/mapping.csv.ttl
```

and our mapping is attached below

[mapping.csv.ttl.txt](https://github.com/SDM-TIB/SDM-RDFizer/files/8060209/mapping.csv.ttl.txt)

Below is the log with the number of triples obtained by rmlmapper:
```
11:16:19.501 [main] INFO  be.ugent.rml.cli.Main               .writeOutputTargets(415) - Target: <rmlmapper://default.store> has 395953 results
```

Thanks in advance

**Comment by eiglesias34** [comment]
Hello @jatoledo,

I have run this dataset and the difference in triples comes from the fact that the SDM-RDFizer does not generate triples in which the original value is None or empty, while the rmlmapper does generate these triples.

I hope this helps

**Comment by jatoledo** [comment]
Hi @eiglesias34 , here attached the dataset :

[dataset](https://delicias.dia.fi.upm.es/nextcloud/index.php/s/spAZ7DEi8sAKqN5/download)

**Comment by eiglesias34** [comment]
Hello @jatoledo,

I just ran the data that you sent me and got this result
[kgc.zip](https://github.com/SDM-TIB/SDM-RDFizer/files/8063881/kgc.zip)

I got the same number of triples. I am running the most recent version of the SDM-RDFizer.

This is the config file I'm running.

```
[default]
main_directory: /home/enrique/Documents

[datasets]
number_of_datasets: 1
output_folder: ./issue/graph
all_in_one_file: no
remove_duplicate: yes
enrichment: yes
name: output
ordered: yes
large_file: false

[dataset1]
name: kgc
mapping: ${default:main_directory}/mapping.ttl```

I hope this works.

**Comment by dachafra** [comment]
problem finally found. The number of results when `large_file: true` is not the expected one

**Comment by eiglesias34** [comment]
I was able to find the problem and fix it.

**Comment by dachafra** [comment]
now, with ordered in true and large_file (yes/no) it works
