### ISSUE TITLE
Different number of triples when ordered is set to NO

### ISSUE THREAD

**Issue by dachafra** [SDM-TIB/SDM-RDFizer#78]
Using the GTFS-Madrid-Bench, mapping in CSV and scale 1, these are the obtained results when ordered is set to no:

large_files=true, ordered=yes --> 395953 triples (this is ok)
large_files=false, ordered=yes --> 395953 triples (this is ok)
large_files=true, ordered=no --> 102993 triples (not ok)
large_files=false, ordered=no --> 397479 triples (not ok)

Seems that the behaviour of the engine isn't correct when ordered is not demanded

**Comment by eiglesias34** [comment]
Hello @dachafra,

I found the issues and fixed them. Please test them out. Please note that I have only updated the code, not the library. After we close this issue I will update the library,

**Comment by dachafra** [comment]
solved
