### ISSUE TITLE
please release on pypi

### ISSUE THREAD

**Issue by WolfgangFahl** [SDM-TIB/SDM-RDFizer#79]
**Describe the bug**
It seems there is no release of this library on pypi yet

**Expected behavior**
Allow to reuse library via entry in requirements.txt in another library

**Additional context**
See https://github.com/somnathrakshit/geograpy3/blob/master/.github/workflows/upload-to-pypi.yml for an automation of the pypi upload

**Comment by WolfgangFahl** [comment]
https://pypi.org/project/rdfizer/ - seem to have it so it's more about a badge in the readme see https://github.com/somnathrakshit/geograpy3/

**Comment by eiglesias34** [comment]
Hello,

I added the badges to the README.
