### ISSUE TITLE
SDM-RDFizer  not able to semantifying rml mapping rules files with join conditions for accents characters 

### ISSUE THREAD

**Issue by rohit252** [SDM-TIB/SDM-RDFizer#82]
snap 1
![snap1](https://user-images.githubusercontent.com/55106484/165765194-6216368f-d9e6-4da8-9cee-47159c51fdad.PNG)
snap 2
![snap2](https://user-images.githubusercontent.com/55106484/165765217-a15cc79b-0800-4f38-a033-c7afb4f22068.PNG)
snap 3
![Capture](https://user-images.githubusercontent.com/55106484/165773147-a31e66d8-692e-45cc-8f14-f24913d33f31.PNG)

SDM-RDFizer not creating triples for the above rml file with the join condition, here  author_1.csv file contains first, last and institution name with the accents characters but when I create another csv file author_2.csv without the accent characters but with the same content as author_1.csv it is working then. 

I have created a test case: 

[SDM-RDFizer.zip](https://github.com/SDM-TIB/SDM-RDFizer/files/8583516/SDM-RDFizer.zip)

1. After unzipping the folder, Inside the SDM-RDFizer folder there is a  folder named  "exam" , in the exam folder we have three csv files, rml mapping rule file and config file for the SDM-RDFizer. 

2. author_reference.csv file contains id  and author_id, I have used this csv file in the triplemap 1 as we can see in the above snap1.

3. author_1.csv file contains first, last and institution names with the accents characters and I am using join conditions to join triple map1 and triple map2 ( please see snap 2 ) 
4. After running the config file for the SDM-RdFizer, I am getting the error, please see snap3 

5. But using author_2.csv if I do the same steps, then it is able to  generate n triples. 

Please see pics: 
![snap 4](https://user-images.githubusercontent.com/55106484/165771336-31a9f679-1b7f-42a2-af21-ee5c6d550504.PNG)
![snap 5](https://user-images.githubusercontent.com/55106484/165771347-4583de15-d2ce-4ae5-9d14-809b0cee204c.PNG)
![snap 6](https://user-images.githubusercontent.com/55106484/165771361-3419f22e-001d-4e2a-acf5-f75d85be165a.PNG)

**Comment by rohit252** [comment]
Hi @eiglesias34 ,

Thank you for the reply, I have used the updated code and it is working on my end also  :))))))

Best,
Rohit

**Comment by eiglesias34** [comment]
Hello again,

I'm going to close the issue now.

Thank you for using the SDM-RDFizer.
Cheers,
Enrique
