### ISSUE TITLE
It would be good to release the SDM-RDFizer as Python Library

### ISSUE THREAD

**Issue by collarad** [SDM-TIB/SDM-RDFizer#9]
Besides the docker, it would be good to release the SDM-RDFizer as Python Library too. So, developer can easily install it, e.g., using _**pip**_ command.

**Comment by dachafra** [comment]
Maybe @daniel-dona could help a bit here as he recently has learnt how to do it

**Comment by daniel-dona** [comment]
I'm working on it right now (https://github.com/daniel-dona/SDM-RDFizer/commit/5f811edd5b3b7d456db2125560fb1322cfa5b5c1), these are some changes implemented:

1. Move `semantify.py` to `__init__.py` as the main library file
2. Implement `__main__.py` as a callable script to use as standalone module `python3 -m rdfizer`
3. Write a setup.py file with the main metadata of the package

I managed to upload a testing build, a bit more testing is needed: https://test.pypi.org/project/rdfizer/3.2rc1596315221/#description

**Comment by daniel-dona** [comment]
Right now installation can be done running this:

`python3 -m pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ -U rdfizer`

Seems to work well as module and library... :smile: 

#29

**Comment by daniel-dona** [comment]
Also, this can be integrated into the same step as Travis CI can also build and upload PyPI packages:

https://github.com/SDM-TIB/SDM-RDFizer/issues/10

**Comment by dachafra** [comment]
done
